extern int *input;
extern int **arr;
void ft_putchar(char c);
void ft_print(int n);
int ft_up_is_correct(int x, int y, int n);
int ft_down_is_correct(int x, int y, int n);
int ft_left_is_correct(int x, int y, int n);
int ft_right_is_correct(int x, int y, int n);
int ft_is_exist(int x, int y , int n);
int ft_is_correct(int x, int y, int n);
void ft_backtracking(int x, int y, int n);
